DROP DATABASE project;
CREATE DATABASE project;
USE project;

DROP FUNCTION SUM_HE;
CREATE AGGREGATE FUNCTION SUM_HE RETURNS STRING SONAME 'MyTest.so';

CREATE TABLE Employees(
	id INTEGER,
	age INTEGER,
	salary longblob NOT NULL, # Bob Loblaw's LONGBLOB
	PRIMARY KEY(id)
);
